### ISSUE TITLE
HOME - Top bar Header fixed height size

### ISSUE THREAD

**Issue by gendeu** [gendeu/klpshop#18]
FROM HOME
![image](https://user-images.githubusercontent.com/57338817/117234045-d510ca80-ae56-11eb-97ec-080fcb1cbc76.png)

TO ITEM LIST
![image](https://user-images.githubusercontent.com/57338817/117234114-f1146c00-ae56-11eb-85b4-1e6818b72c3a.png)

**Comment by gendeu** [comment]
Notif the Header Bar on top became small everytime you go to Item list (products or services). Please make it height size fixed wherever user go. Thank u very much divine.

**Comment by Ryaan10** [comment]
> Please notice the Header Bar became small everytime you go to Item list (products or services). Please make it height size fixed wherever user go. Thank u very much divine.

Noted po sir Deo

**Comment by Ryaan10** [comment]
Hahaha
