### ISSUE TITLE
GENERAL - Product or Service item filtering design and add neutral filter

### ISSUE THREAD

**Issue by gendeu** [gendeu/klpshop#53]
![image](https://user-images.githubusercontent.com/57338817/117604011-ed4e5580-b186-11eb-8a33-4dd17d189303.png)

Sortings works well but it doesnt seem seamless because the page jumps or repositions itself per categorial choice 

- No way to delete their filters (Must Have Show All option)

**Comment by Ryaan10** [comment]
Add rating
